# Generated by Django 5.0.3 on 2024-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0005_alter_expenses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
