# Generated by Django 5.0.3 on 2024-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boost', '0007_alter_expenses_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
